language: haskell
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone --branch tower-9 https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
  - git clone https://github.com/galoisinc/ivory-tower-stm32
  - export BSP_REPO=$PWD/ivory-tower-stm32
install:
  - cabal install alex
  - cabal install happy
script:
  - arm-none-eabi-gcc --version
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO BSP_REPO=$BSP_REPO make $ENV_TEST_TARGET
ghc:
  - 7.6.3
  - 7.8.3
env:
  - ENV_TEST_TARGET=ivory-hxstream
  - ENV_TEST_TARGET=ivory-px4-hw
  - ENV_TEST_TARGET=ivory-px4-tests
